apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebcalculator
  namespace: default
spec:
  replicas: 4 # Number of replicas
  selector:
    matchLabels:
      app: myapp-v1
  template:
    metadata:
      labels:
        app: myapp-v1
    spec:
      containers:
        - name: mycontainer
          image: surya9961/javacalculator:v1
          ports:
            - containerPort: 8080
